language: python
sudo: required
python:
- 3.7
addons:
  ssh_known_hosts:
  - 47.101.147.73
before_install:
#- sudo apt-get install sshpass
- openssl aes-256-cbc -K $encrypted_84adcc736132_key -iv $encrypted_84adcc736132_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
install:
- pip install -r requirements.txt
script:
- python test.py
after_success:
# - echo '#!/bin/bash' >> test.sh
# - echo 'trap "pkill -f $(basename $0);exit 1" SIGINT SIGTERM EXIT ERR' >> test.sh
# - echo 'ssh zhangkang@47.101.147.73 -o StrictHostKeyChecking=no "bash ~/DialogueRobot/deploy.sh" &' >> test.sh
# - echo 'echo "OK"' >> test.sh
# - bash test.sh

- ssh zhangkang@47.101.147.73 -o StrictHostKeyChecking=no "bash ~/DialogueRobot/deploy.sh" 
#- sshpass -p 'zhangkang' ssh zhangkang@47.101.147.73 "bash ~/DialogueRobot/deploy.sh"

